apiVersion: v1
entries:
  klovercloud-agent-operator:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-01-06T03:26:21.028243732+06:00"
    description: A Helm chart for Klovercloud Agent
    digest: cc8fb6c7f88b56f2e903e7fe80cdb61a41145d7aea4248d82dcdb8e785134d7c
    name: klovercloud-agent-operator
    type: application
    urls:
      - klovercloud-agent-operator-1.2.0.tgz
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-07-02T03:26:21.028243732+06:00"
    description: A Helm chart for Klovercloud Agent
    digest: cc8fb6c7f88b56f2e903e7fe80cdb61a41145d7aea4248d82dcdb8e785134d7b
    name: klovercloud-agent-operator
    type: application
    urls:
    - klovercloud-agent-operator-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-02T03:26:21.023455175+06:00"
    description: A Helm chart for Klovercloud Agent
    digest: d45e54c7c9817b1f09d7b0f4c1f336f4068cabe34f436421e2186422a054737a
    name: klovercloud-agent-operator
    type: application
    urls:
    - klovercloud-agent-operator-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-02T03:26:20.998635694+06:00"
    description: A Helm chart for Klovercloud Agent
    digest: 0812e3eda380f97ec9c9ec337c6eed5fa7c6482825b67a44d9170ac634695622
    name: klovercloud-agent-operator
    type: application
    urls:
    - klovercloud-agent-operator-0.2.6.tgz
    version: 0.2.6
  klovercloud-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-02T03:26:21.062230281+06:00"
    description: A Helm chart for Klovercloud Helm Chart
    digest: bdafd3ded1b9192bbbab30e209de95aecab665abb71e87b5541db823afcd0a2d
    name: klovercloud-operator
    type: application
    urls:
    - klovercloud-operator-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2025-07-02T03:26:21.046785946+06:00"
    description: A Helm chart for Klovercloud Helm Chart
    digest: 39faee6ab64ffb51f58824c261a4e32a3377be3be7558503e2cb0a20b2d75f73
    name: klovercloud-operator
    type: application
    urls:
    - klovercloud-operator-0.2.5.tgz
    version: 0.2.5
generated: "2025-07-02T03:26:20.709110961+06:00"
